Tezster kp
Tezsure/Tezster pull request #22
Opened 2020-02-19 14:10 UTC by kapiltez

2020-02-19 14:39 UTC, jvtezsure commented
Why is there empty .gitignore file. Let's not commit that.

2020-02-20 06:18 UTC, jvtezsure commented on README.md
> +This will download the docker image containing pre-build tezos nodes on your system. You need to run setup only once. After that run,
'pre-built tezos nodes and baker' on your system

2020-02-20 06:18 UTC, jvtezsure commented on README.md
> +It will activate Tezos alpha. Now you will have three nodes running successfully on port 18731, 18732 and 18733. To see the nodes running run following commands as the root (super user)
We need to udpate this description with relevant info. We only have 18731 port.

2020-02-20 06:18 UTC, jvtezsure commented on README.md
> +It will activate Tezos alpha. Now you will have three nodes running successfully on port 18731, 18732 and 18733. To see the nodes running run following commands as the root (super user)
Also no super user required now

2020-02-20 06:18 UTC, jvtezsure commented on README.md
> +To transfer tezos from account to another account , You don't have to Bake your blocks because its taken care automatically
you don;t have to bake your blocks because a baker is running for your local node and it bakes automatically.

2020-02-20 06:18 UTC, jvtezsure commented on README.md
> +tezster set-provider http://localhost:18731
give one more example with tezster set-provider <tezster.tech or cyptonomic node>

2020-02-20 06:18 UTC, jvtezsure commented on README.md
>  sudo tezster stop-nodes
Need to update description for stop-nodes and lsof command
you can remove lsof command as of now.

2020-02-20 06:18 UTC, jvtezsure commented on package.json
> +  "name": "tezster2",
you shouldn't be changing the version and name of the package.

2020-02-20 06:18 UTC, jvtezsure commented on package.json
> +    "dockerode": "*",
Mention specific version. Else it may start breaking without knowing.

2020-02-20 06:18 UTC, jvtezsure commented on tezster-manager.js
> +"use strict";
use single quotes.

2020-02-20 06:18 UTC, jvtezsure commented on tezster-manager.js
> +  if ((f = findKeyObj(config.identities, pkh))) {
Why extrac () arounf f = findKeyObj(config.identities, pkh). Can you please fix this for whole file and any other place?

2020-02-20 06:18 UTC, jvtezsure commented on tezster-manager.js
> +    const contract = fs.readFileSync(contractPath, "utf8");
prefer single quotes everywhere.

2020-02-20 06:18 UTC, jvtezsure commented on tezster-manager.js
> +          );
If you're breaking a single line into multiple line, make sure it's indented properly.

2020-02-20 06:18 UTC, jvtezsure commented on tezster-manager.js
> +  } catch (error) {
Why do we need to have new line for string. Why can't we have 'return outputError(`Contract deployment has failed : ${JSON.stringify(result)}`);' in single line?
I think your IDE has forced style changes. Can we make sure we have some consistent maintanable style practices?

2020-02-20 06:18 UTC, jvtezsure commented on tezster-manager.js
> +  let contractAddress = "";
single quote. pls Fix it wherever it has been changed.

2020-02-20 06:18 UTC, jvtezsure commented on tezster-manager.js
> +  activateAlphanetAccount: activateAlphanetAccount
I believe you don;t have much changes w.r.t fnctioanlity in this file. Make sure you're adding only changes which are required.

2020-02-20 06:18 UTC, jvtezsure commented on tezster.js
> +const cp = require("child_process");
give meaning full variable name.

2020-02-20 06:18 UTC, jvtezsure commented on tezster.js
> +    );
uset tezster-manager, logger with relevant tag (info, error, debug) for any logging.

2020-02-20 06:18 UTC, jvtezsure commented on tezster.js
> +  docker.listContainers(function(err, containers) {
Isn't there any easy way to find the containerId for our container and  just stop that?
this is not recommendable.

2020-02-20 06:18 UTC, jvtezsure commented on tezster.js
> +            cp.exec(`docker container stop $(docker container ls -q --filter name=tezster*) ; docker rm /tezster`,
why can't we use dockerode APIs here?

2020-02-20 06:45 UTC, kapiltez commented on README.md
> +It will activate Tezos alpha. Now you will have three nodes running successfully on port 18731, 18732 and 18733. To see the nodes running run following commands as the root (super user)
For checking running nodes via running lsof -i:18731, user need to run suing sudo

2020-02-20 06:55 UTC, kapiltez commented on README.md
> +To transfer tezos from account to another account , You don't have to Bake your blocks because its taken care automatically
have modified accordingly.

2020-02-20 07:14 UTC, kapiltez commented on README.md
> +tezster set-provider http://localhost:18731
added example for "tezster set-provider http://testnet.tezster.tech".

2020-02-20 07:20 UTC, kapiltez commented on package.json
> +  "name": "tezster2",
I did that for my own npm publish for testing purpose, anyway changed back.

2020-02-20 07:22 UTC, kapiltez commented on tezster-manager.js
> +"use strict";
yes that got changed due to linting. Revert backed to single quote and other formatting also.

2020-02-20 07:23 UTC, kapiltez commented on tezster-manager.js
> +          );
That was due to lenting. reverted back.

2020-02-20 07:25 UTC, kapiltez commented on tezster-manager.js
> +  activateAlphanetAccount: activateAlphanetAccount
I didn't changed this. THis got due to the VS Code lenting.

2020-02-20 07:30 UTC, kapiltez commented on tezster.js
> +  docker.listContainers(function(err, containers) {
yes, I have given name to our container and stopping to that particularly now.

2020-02-20 07:31 UTC, kapiltez commented on tezster.js
> +  docker.listContainers(function(err, containers) {
I have changed accordingly  in the code.

2020-02-20 07:32 UTC, kapiltez commented on README.md
> +It will activate Tezos alpha. Now you will have three nodes running successfully on port 18731, 18732 and 18733. To see the nodes running run following commands as the root (super user)
Anyway I have removed lsof command. But for node check user have to run sudo lsof -i:18731.

2020-02-20 07:38 UTC, kapiltez commented on package.json
> +    "dockerode": "*",
okay done.

2020-02-20 07:51 UTC, kapiltez commented on tezster-manager.js
> +  } catch (error) {
I have reverted back the style changes.

2020-02-20 09:06 UTC, kapiltez commented on tezster-manager.js
> +  if ((f = findKeyObj(config.identities, pkh))) {
braces are being removed in a new commit.

2020-02-20 09:21 UTC, kapiltez commented on tezster.js
> +            cp.exec(`docker container stop $(docker container ls -q --filter name=tezster*) ; docker rm /tezster`,
we can use it, but with this also we are achieving the goals we want.

2020-02-20 12:44 UTC, jvtezsure requested changes

2020-02-20 12:44 UTC, jvtezsure commented on tezster.js
> +var auxContainer;
give meaningful variable name.

2020-02-20 12:44 UTC, jvtezsure commented on tezster.js
> +            docker.pull("tezsureinc/tezster:1.0.0", (error, stream) => {
Move this tag to a global constant so that we just have to change that whenever we want to update docker build version.

2020-02-20 12:44 UTC, jvtezsure commented on tezster.js
> +              Image: "tezsureinc/tezster:1.0.0",
Use this from gloabal constant.

2020-02-20 12:44 UTC, jvtezsure commented on tezster.js
> +              name: "tezster",
move container name to a constant and use that.

2020-02-20 12:44 UTC, jvtezsure commented on tezster.js
> +            "No inbuilt nodes found on system. Run 'tezster setup' comamnd for build the nodes."));
+1 for handling this.

2020-02-20 12:44 UTC, jvtezsure commented on tezster.js
> +        if (__stdout.includes("tezsureinc/tezster:1.0.0\n"))
Use image name constant to check here.

2020-02-20 12:44 UTC, jvtezsure commented on tezster.js
> +        console.log(tezsterManager.outputError("No Nodes are running...."));
+1 for this.

2020-02-20 13:46 UTC, kapiltez commented on tezster.js
> +            docker.pull("tezsureinc/tezster:1.0.0", (error, stream) => {
defined image tag as "imageTag" global constant variable.

2020-02-20 13:47 UTC, kapiltez commented on tezster.js
> +              name: "tezster",
defined container name as "containerName" global constant variable.

2020-02-20 13:48 UTC, kapiltez commented on tezster.js
> +        if (__stdout.includes("tezsureinc/tezster:1.0.0\n"))
I have committed with changes.

2020-02-20 13:50 UTC, kapiltez commented on tezster.js
> +              Image: "tezsureinc/tezster:1.0.0",
I have committed with same changes. Please review.

2020-02-20 16:43 UTC, jvtezsure commented on tezster.js
> +            cp.exec(`docker container stop $(docker container ls -q --filter name=tezster*) ; docker rm /tezster`,
Using a proper API is much clearner way to do things. It matters how you reach to your goal.

2020-02-20 16:48 UTC, merged